### ISSUE TITLE
The plugin tries to bump the "workspace:" dependencies versions, even though I don't need to

### ISSUE THREAD

**Issue by e965** [release-it-plugins/workspaces#112]
Demonstration:

![image](https://github.com/release-it-plugins/workspaces/assets/18071040/f9f6a4fe-9c56-48e0-8cfb-570390c2fe43)

This way of specifying dependency versions within monorepositories is a (relatively) common practice:
* https://pnpm.io/workspaces#publishing-workspace-packages
* https://yarnpkg.com/features/workspaces#cross-references

I understand that the current behaviour has a right to exist, but I'd still like to have an option to disable it.

**Comment by e965** [comment]
Oops, just now saw that this functionality seems to be developed here - https://github.com/release-it-plugins/workspaces/pull/110

**Comment by rwjblue** [comment]
Released in 4.2.0+ (thanks @NullVoxPopuli!)
