### ISSUE TITLE
inactionable warning

### ISSUE THREAD

**Issue by hjdivad** [release-it-plugins/workspaces#47]
```
WARNING @eslint-plugin-graphql-fragment-import/example: Skip publish (package is private)
```

I understand the cases where this warning provides value, but for me this warning is telling me "WARNING: doing the thing you asked" which is not actionable.

Is there a good way to silence this warning?  It seems my best option right now is to [duplicate my list of workspaces](https://github.com/rwjblue/release-it-yarn-workspaces#configuration) by specifying them in both `package.json:.workspaces` as well as `package.json:.release-it.plugins.release-it-yarn-workspaces.workspaces` but this seems potentially error-prone to me.

Thoughts on a config to opt-out of this warning?

**Comment by rwjblue** [comment]
> It seems my best option right now is to duplicate my list of workspaces by specifying them in both package.json:.workspaces as well as package.json:.release-it.plugins.release-it-yarn-workspaces.workspaces but this seems potentially error-prone to me.

Ya, there are cases where you _need_ to duplicate the config (that is why I added those options), but IMHO this case should not need it.

I think we should remove the warning (and move it to a debugging log instead), but I _do_ think we need to work a bit more on progress indicators (https://github.com/rwjblue/release-it-yarn-workspaces/issues/31).
