### ISSUE TITLE
Support custom registry for scoped packages

### ISSUE THREAD

**Issue by hnrchrdl** [release-it-plugins/workspaces#64]
The registry is not picked up correctly for scoped packages.

The registry is currently retrieved from publishConfig option like this

```js
getRegistry() {
  return this.getContext('publishConfig.registry') || NPM_DEFAULT_REGISTRY;
}
```

This fails for scoped packages, for example with such a configuration:

```
"publishConfig": {
  "@namespace:registry": "https://path-to-custom-registry/"
}
```

Here is [how release-it retrieves the registry name currently](https://github.com/release-it/release-it/blob/d702675ecdb328eb987df6d6f0c2247be6d2fb5b/lib/plugin/npm/npm.js#L190).

I could try to create a MR if you like.

**Comment by scalvert** [comment]
Resolved in #65
