### ISSUE TITLE
Make this work generically with workspaces

### ISSUE THREAD

**Issue by runspired** [release-it-plugins/workspaces#69]
considering both npm and pnpm offer workspaces now with near identical APIs :)

**Comment by scalvert** [comment]
I think the idea we had was to rename/genericize this package, as this isn't really related only to `yarn` anymore. It makes sense to call it `release-it-workspaces` or something, and of course test the different package manager variants.

**Comment by gabrielcsapo** [comment]
https://github.com/gabrielcsapo/release-it-workspaces I have published a repo with the name change and support for 15, more than happy to merge it back in if we want to rename this repo or deprecate it and I can transfer to @rwjblue if needed.

**Comment by gabrielcsapo** [comment]
I feel like a rename could be done to https://github.com/rwjblue/release-it-lerna-changelog as this could support workspaces more generically as well.

**Comment by scalvert** [comment]
@gabrielcsapo I'd definitely prefer to merge changes back in. There's also a separate PR for ESM to support 15 - #73

**Comment by scalvert** [comment]
It could, so long as it's tested with other dependency tools.
