### ISSUE TITLE
Make generic, support pnpm?

### ISSUE THREAD

**Issue by NullVoxPopuli** [release-it-plugins/workspaces#70]
yarn@v1 has too many bugs around transient deps and peers.

Is it worth it for this package to support pnpm (or any package manager)?
Or should all the code just be copied to a new package focusing on how pnpm defines workspaces? 
(in a pnpm-workspace.yaml file, as opposed to in package.json)

**Comment by scalvert** [comment]
This should be fairly straightforward, allowing us to read the `packages` configuration from the `pnpm-workspace.yaml` file vs. the package.json, as per https://pnpm.io/pnpm-workspace_yaml (as you previously mentioned).

**Comment by scalvert** [comment]
Released in https://github.com/release-it-plugins/workspaces/releases/tag/v3.2.0
