### ISSUE TITLE
ERROR Cannot destructure property 'distTag' of 'context.@release-it-plugins/workspaces' as it is undefined

### ISSUE THREAD

**Issue by jakobo** [release-it-plugins/workspaces#80]
**Version Info**
* `"release-it": "^15.1.3"`
* `"@release-it-plugins/workspaces": "^3.1.0"`
* node: 14.9.0
* npm: 6.14.16
* yarn: 3.2.0

**.release-it.json**
```json
{
  "plugins": {
    "@release-it-plugins/workspaces": true
  },
  "npm": false,
  "git": {
    "commitMessage": "chore: Releases version v${version}"
  },
  "hooks": {
    "before:init": [
      "syncpack list-mismatches",
      "syncpack format",
      "yarn workspaces foreach -pitv --no-private run release:before:init"
    ]
  }
}
```

**Explanation**
I upgraded from what was the old release-it yarn plugin to the one mentioned in the release-it readme. When running `release-it --preRelease=next`, I get the following error at the push step:

```
✔ syncpack list-mismatches
✔ syncpack format
✔ yarn workspaces foreach -pitv --no-private run release:before:init

🚀 Let's release taskless (3.0.0-next.0...3.0.0-next.1)


Changelog:
* deps: Updates release-it to latest (dc0efd1)


Changeset:
 M package.json

? Commit (chore: Releases version v3.0.0-next.1)? Yes
? Tag (3.0.0-next.1)? Yes
? Push? Yes
ERROR Cannot destructure property 'distTag' of 'context.@release-it-plugins/workspaces' as it is undefined.
```

**Triage**
From what I can gather, it looks like https://github.com/release-it-plugins/workspaces/blob/master/index.js#L133 is the culprit, though it isn't clear if that's because we need to read the `distTag` again for ourselves, or release-it is no longer passing the distTag to plugins.

**Comment by scalvert** [comment]
Thanks for reporting. Looks like there's a gap in our tests. I'll take a look and publish a fix as soon as possible.

**Comment by scalvert** [comment]
Debugging this, it appears that `release-it` is trimming off the plugins' scope when loading.

<img width="1090" alt="Screen Shot 2022-07-25 at 9 37 32 AM" src="https://user-images.githubusercontent.com/180990/180830076-0bbccff4-8498-478e-8549-ce004b9ddec4.png">

We do have [tests that cover destructuring the `distTag`](https://github.com/release-it-plugins/workspaces/blob/master/__tests__/plugin-test.js#L512), but they [artificially add the package name as a property on the context](https://github.com/release-it-plugins/workspaces/blob/master/__tests__/plugin-test.js#L25), so it doesn't reflect how plugins are loaded. 

I'm looking into it further to see how best to manage this.

**Comment by scalvert** [comment]
I opened https://github.com/release-it/release-it/pull/926 to try to address this.

**Comment by scalvert** [comment]
Released in https://github.com/release-it-plugins/workspaces/releases/tag/v3.2.0
